title: Nick Norcross' Homepage
author: nnorx
email: nick.norcross@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My homepage hosted by GitHub Pages.

# social links
github_username:  nnorx # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
